---
title: "ex-9"
author: "Vignesh"
date: "28 September 2023"
output: html_document
---

## mutate() Exercises

1. Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they're not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.

Set a duplicate data set name as flights_sml and select variables( year to day and departure time,scheduled departure time)


1.1 Create time variables denoting number of minutes since midnight for variables dep_time and sched_dep_time


2. Compare air_time with arr_time - dep_time. What do you expect to see ? What do you see? What do you need to do to fix it?



I see that the air_time and (arr_time - dep_time) difference is different.

3. Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?


4. Find the 10 most delayed flights using a ranking function.


4.1 How do you want to handle ties ? Carefully read the documentation for min_rank().



5. What does 1:3 + 1:10 return ? why ?



6. What trignometric functions does R provide ?


